name : Add outside collaborators
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Github Username to add'
        required: true
      orgs:
        description: 'comma seperated list of organisations'
        required: true
jobs:
  add-collaborators:
    runs-on: windows-latest
    steps: 
      - name: Add user as read-only collaborator
        shell: pwsh
        env: 
          GH_PAT: ${{ secrets.GH_PAT }}
          TARGET_USER: ${{ github.event.inputs.username }}
          ORG_LIST: ${{ github.event.inputs.orgs }}
        run: | 
        #authorization of GIthub
            $headers = @{
              Authorization = "token $env:GH_PAT"
              Accept = "application/vnd.github+json"
            }
               #split comma seperated ORGS into an array
              $orgs = $env:ORG_LIST -split ','
              foreach ( $org in $orgs ) {
                write-Host " Processing organisation: $org"
                #Get all repositories in the org
                $repos = (Invoke-RestMethod -Headers $headers -Uri ""https://api.github.com/orgs/$org/repos?per_page=100").full_name
                foreach ( $repo in $repos ) {
                Write-Host "Adding $env:tEARGET_USER to $repo (read-only)"
                Invoke-RestMethod -Method Put -Headers $headers ` -Uri "https://api.github.com/repos/$repo/collaborators/$env:TARGET_USER" `
                -Body '{"permission": "pull"}'
            }
          }
