name : Add outside collaborators
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Github Username to add'
        required: true
      orgs:
        description: 'comma seperated list of organisations'
        required: true
jobs:
  add-collaborators:
    runs-on: windows-latest
    steps: 
      - name: Add user as read-only collaborator
        shell: pwsh
        env: 
          GH_PAT: ${{ secrets.GH_PAT }}
          TARGET_USER: ${{ github.event.inputs.username }}
          ORG_LIST: ${{ github.event.inputs.orgs }}
        run: | 
          # authorization of GIthub
          $headers = @{ Authorization = "token $env:GH_PAT" }
          $orgList = $env:ORGS -split ","
          foreach ( $org in $orgs ) {
            Write-Host "Processing organisation: $org"
                #Get all repositories in the org
              $repos = Invoke-RestMethod -Headers $headers -Uri "https://api.github.com/orgs/$org/repos?per_page=100"
              foreach ( $repo in $repos ) {
                $repoName = $repo.name
                Write-Host "Adding $env:TARGET_USER to $org/$repoName"
                $body = @{ permission = "pull" } | ConvertTo-Json
                try {
                    $response = Invoke-RestMethod `
                      -Method Put `
                      -Headers $headers  `
                      -Uri "https://api.github.com/repos/$repo/collaborators/$env:TARGET_USER" `
                      -Body $body `
                      -ContentType "application/json"
                     if ($response) {
                           Write-Host " Success! API Response: $($response | ConvertTo-Json)" 
                      } else {
                           Write-Host "No Response"
            }
            }
            catch {
              Write-Host "failed to add $env:TARGET_USER to $repoName"
              }
            }
          }   

